# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#========
# Site settings
#========
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Human-Computer Interaction & Design Lab.
email: hcid@hcid.snu.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

#========
# Build settings
#========
destination: _site
markdown: kramdown
plugins:
  - jekyll-feed

# Includes
include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclue: ['node_modules']
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/s
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# TODO: Update the code with secondary menu
nav_list:
  Home: ['Home', '/']
  #News: ['News', '/news']
  People: ['People', '/people']
  Research: ['Research', '/research']
  Publications: ['Publications', '/publications']
  Courses: ['Courses', '/courses']


sass:
  sass_dir: _sass

relative_permalinks: false

collections:
  news:
    output: true
    permalink: /:collection/:year/:month/:day/
  people:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:slug
  courses:
    output: true
    permalink: /:collection/:slug